version: "3.8"
services:
  api:
    image: peroxy12/pokemon-catch-guide-api:latest
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - API_SECRET_HASH=${API_SECRET_HASH}
    restart: always
    user: "${UID}:${GID}"
    volumes:
      - ./pokemon.db:/home/node/app/pokemon.db:rw
    networks:
      - pokenet
  nginx:
    image: nginx:1.19.7-alpine
    restart: always
    ports:
      - "443:443"
    networks:
      - pokenet
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/live/api.peroxy.tech/fullchain.pem:/etc/letsencrypt/live/api.peroxy.tech/fullchain.pem
      - /etc/letsencrypt/live/api.peroxy.tech/privkey.pem:/etc/letsencrypt/live/api.peroxy.tech/privkey.pem
    depends_on:
      - api
networks:
  pokenet:
    name: pokenet_network
